### ISSUE TITLE
Error in Adding to a Collection

### ISSUE THREAD

**Issue by Francisder** [neo-con/chromadb-tutorial#1]
Help !

Im new to ChromaDB.

Ive been going through your tutorial but for some reason I cannot ADD to a collection.

Ive enclosed a screenshot of the error im getting in IDLE.

Has anyone had a similar error ?  I suspect its an installation issue.

![ChromaDB](https://github.com/neo-con/chromadb-tutorial/assets/36877394/552eebb5-3a07-4010-9936-7f09c08cae26)

Allen

**Comment by neo-con** [comment]
Looks like an issue with the ONNX model. Have you tried re-installing? Also, test this out in a virtual environment. 

FYI, It may be best to post this bug/issue directly in [Chroma's](https://github.com/chroma-core/chroma) repo.

**Comment by neo-con** [comment]
Hello @Francisder , I see you have posted on the main repo. They suggested re-downloading the model. Has this worked out for you?

**Comment by neo-con** [comment]
Closing this issue.

https://github.com/chroma-core/chroma/issues/1633
